[STORAGE]
SQLITE_DB = "db/devika.db"
SCREENSHOTS_DIR = "screenshots"
PDFS_DIR = "pdfs"
PROJECTS_DIR = "projects"
LOGS_DIR = "logs"
REPOS_DIR = "repos"

[API_KEYS]
BING = "<YOUR_BING_API_KEY>"
CLAUDE = "<YOUR_CLAUDE_API_KEY>"
NETLIFY = "<YOUR_NETLIFY_API_KEY>"
OPENAI_TYPE = "<YOUR_OPENAI_TYPE>"
OPENAI = "<YOUR_OPENAI_OR_AZURE_OPENAI_API_KEY>"
API_VERSION = "2024-02-15-preview"
AZURE_OPENAI_ENDPOINT = "<YOUR_AZURE_OPENAI_ENDPOINT>"

[API_ENDPOINTS]
BING = "https://api.bing.microsoft.com/v7.0/search"
