[STORAGE]
SQLITE_DB = "db/devika.db"
SCREENSHOTS_DIR = "screenshots"
PDFS_DIR = "pdfs"
PROJECTS_DIR = "projects"
LOGS_DIR = "logs"
REPOS_DIR = "repos"

[API_KEYS]
BING = "<YOUR_BING_API_KEY>"
CLAUDE = "<YOUR_CLAUDE_API_KEY>"
NETLIFY = "<YOUR_NETLIFY_API_KEY>"
OPENAI = "<YOUR_OPENAI_API_KEY>"
TOGETHER = "2bd5fb91b0ddcd370d17067dec905b7e27cf9050cadc8725bec5b57ee4f1b0c2"

[API_ENDPOINTS]
BING = "https://api.bing.microsoft.com/v7.0/search"
