version: '3.8'
services:
  devika-python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - sqllitedb:/db
  devika-ui:
    build:
      context: ./ui  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
volumes:
  sqllitedb: